### ISSUE TITLE
msys2 pacman package

### ISSUE THREAD

**Issue by dsisnero** [red-data-tools/GR.rb#26]
It would be nice to install on windows with msys2 package and rubygems

gemspec.metadata['msys2_mingw_dependencies'] = 'gr'

**Comment by kou** [comment]
Could you submit a pull request that creates `mingw-w64-gr` to https://github.com/msys2/MINGW-packages?
Then we can use the configuration.

**Comment by kojix2** [comment]
https://github.com/sciapp/gr/issues/100

**Comment by kojix2** [comment]
It would be great to be able to install GR from the mingw package on Windows.

But honestly, I don't know enough time and knowledge to build the C library on Windows. 
Trying to figure out how to compile a package is time-consuming especially when they do not familiar with Windows. The Sciapp team has not been very eager to provide custom packages for package management systems like `APT` (Advanced Packaging Tool) or `homebrew`. Instead, they provide binary files on the Github release page. (Like they don't care about the opportunity to get more users.)

I think this is their attitude towards responsibility, trying to control things by making the release process as simple as possible. Their software development is sustainable, and I think that is the why GR is an outstanding plotting library among others. 

So you will have to provide the MinGW package yourself. However, there are more GR users today. Nim and crystal bindings have created recently. I'm sure there are people in the world who need a MinGW package just as much as you do. As @kou wrote above, you can help them by sending a pull request or help them discover the problem. Maybe someone help you. 

Long sentence and no clear solution. I'm sorry for that...

**Comment by kou** [comment]
Done: https://github.com/msys2/MINGW-packages/pull/6521

**Comment by kojix2** [comment]
@kou 
Your work is always incredible...

@dsisnero 
The package is done.
It would be helpful if you could help us maintain the package.

* Report bugs if you find it.
* Send PR to update the GR version.

**Comment by dsisnero** [comment]
Thank you so much!  I will help as much as I am able.

Thanks again
