### ISSUE TITLE
Porting GRUtils to GR.rb

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/GR.rb#29]
* https://github.com/heliosdrm/GRUtils.jl
* https://heliosdrm.github.io/GRUtils.jl/latest/

**Comment by kojix2** [comment]
## General
* _min(a)
* _max(a)
* hasnan(a)
* lookup

## Colors
* COLOR_SCHEMS
* BASIC_COLORS
* SERIES_COLORS
* COLOR_INDICES
* resetcolors
* rgb
* color
* colorindex
* COLORMAPS
* colormap
* to_rgba
* applycolorscheme
* colorscheme

## Geometries
* struct Geometry
  * kind
  * x
  * y
  * c
  * spec
  * label
  * attributes
* Geometry(constructor)
* geometries
* **draw**

## Axes
* AxisRange
* AxisTickData
* struct Axes
  * kind
  * ranges
  * tickdata
  * ticklabels
  * perspective
  * camera
  * option
* Axes(constructor)
* minmax
* extrema64
* fix_minmax
* adjustranges!
* set_ticks
* set_axis
* set_ticklabels!
* ticklabel_fun
* set_scale
* _rotate!
* _tilt!
* _focus!
* set_camera
* graham_hull
* axes3frame
* fillaxesbackground
* draw
* draw_polaraxes
* _tickcharheight

## Legends
* LEGEND_KINDS
* LEGEND_LOCATIONS
* struct Legend
* Legend(constructor)
* legend_box
* draw
* guide

## Colorbars
*  struct Colorbar
  * range
  * tick
  * scale
  * margin
  * colors
* EMPTYCOLORBAR
* Colorbar(constructor)
* draw

## Plotobjects

## Text

## Figures

## Frontend

## Attributes

## Animations

**Comment by kojix2** [comment]
The biggest problem with the current GR.rb is that it is a Ruby library, but it is not object-oriented. 
GRUtils and GR.jl are different. 
Asymptotic migration is unlikely to be possible. So, I will split the repository.

**Comment by kou** [comment]
Should we create https://github.com/red-data-tools/GRUtils.rb ?

**Comment by kojix2** [comment]
Umm.. Maybe no.

I will create a kojix2/GRUtils.rb to add a ruby object to GR.rb.
This will be an experiment. 
There will be a lot of changes, including the structure of the objects. 
I will report back when I think GRUtis.rb is ready to integrate GR.rb.

**Comment by kojix2** [comment]
But yes. I agree.

I think the "risk of not being able to complete GRUtils.rb" is much greater than the "risk of not being able to create GRUtils correctly".

To be honest, I'm not confident that I can complete GRUtils.rb.
So I think I should move the source code to red-data-tools as soon as possible so that other people besides me have a chance to see it.

That way, I'll be motivated. It's important to stay motivated.

**Comment by kou** [comment]
OK. Please notify us when you are ready. :-)
