### ISSUE TITLE
Support saving a plot directly to a file without opening up Qt?

### ISSUE THREAD

**Issue by fapdash** [red-data-tools/GR.rb#45]
I'd like to us GR.rb to auto generate PNGs for a website a part of the build process.
Is it possible to use GR.rb without opening the GKS QtTerm window with the preview?
Do you intend to support this use case?

**Comment by kojix2** [comment]
Hello. @fapdash 

The short answer is.
Set the environment variable GKS_WSTYPE, I think it will prevent the Qt window from showing up.
See https://gr-framework.org/workstations.html#workstation-types

The longer answer is
I haven't thought about using GR.rb on the server, so I don't know how best to do that. Perhaps GR.rb needs to be improved.

**Comment by kojix2** [comment]
> No Output
>
> To use GR without generating output, you can use workstation type 100. You will still be able to explicitly write output to a file using gr_beginprint() or similar GR functions, but there will be no implicit output to an application or file.

https://gr-framework.org/workstations.html#no-output

```ruby
export GKS_WSTYPE=100
ruby examples/save_figures.rb
ruby examples/save_video.rb
```

Images will be output to the example/savefig directory.

```sh
ls examples/savefig
# image.bmp  image.jpg  image.png  image.svg
# image.gif  image.pdf  image.ps   image.tif
```

GR.savefig is a high-level API for GR::Plot. Use `GR.beginprint` and `GR.endprint` if you are creating a graph using the low-level native API.

See https://github.com/red-data-tools/GR.rb/wiki/Save-Plot-to-a-file

**Comment by fapdash** [comment]
Thank you, seems to work great!

It also works when setting the ENV via Ruby:

```ruby
require 'fileutils'
require 'gr/plot'

ENV["GKS_WSTYPE"] = "100"
FileUtils.mkdir_p 'build/images'

x = [1, 2, 3, 4, 5]
y = [1, 8, 27, 64, 125]

GR.plot(x, y)
GR.savefig('build/images/plot.svg')
```

**Comment by fapdash** [comment]
I think it would be nice to add a note about this to either the README or the wiki. wdyt?

**Comment by kojix2** [comment]
You are right. 
Where do you think I should write the explanation in the README?
If you send me a pull request, I can add you to the contributors.

![image](https://user-images.githubusercontent.com/5798442/126852245-bd422a16-76d1-479c-b91d-3b871d0b4cf1.png)
